@startuml
skinparam componentStyle rectangle
package "API/Backend" {
  [Api]
  [Altinn]
  [Kafka]
  [Autentisering]
  [Repository]
}

package "Frontend" {
  [WebApp]
}

cloud "Sky/eksterne systemer" {
  [Kafka/Aiven]
  [Id-Porten]
}

package "Integrasjoner i Nav/Nais" {
  [Altinn proxy]
  [Pam-janzz]
}

actor Arbeidsgiver

[Nais/TokenX]

database "Postgres" {
  folder "Cloud SQL/permitteringsskjema-api" {
    [permitteringsskjema-api-db]
  }
}

Arbeidsgiver --> [WebApp] : Oppretter og sender skjemaer
[Kafka] --> [Kafka/Aiven] : Legger meldinger på topic for videre behandling
[Autentisering] --> [Nais/TokenX] : Henter nye tokens for bruk til eksterne api
[WebApp] --> [Nais/TokenX] : Henter nye tokens for bruk til backend-api
[WebApp] --> [Api]
[WebApp] --> [Id-Porten] : Autentiserer
[Api] --> [Altinn]
[Api] --> [Kafka]
[Api] --> [Autentisering]
[Api] --> [Repository]
[Api] --> [Pam-janzz] : Henter stillingsbeskrivelser
[Altinn] ---> [Altinn proxy] : Henter roller
Repository--> Postgres
@enduml